Traceback (most recent call last):
  File "c:\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\python39\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\python39\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\python39\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "c:\python39\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\python39\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sympy as sym
a, b, f = sym.symbols('a, b, f', real=True, positive=True)
t = sym.symbols('t', real=True)
i = sym.I
œÄ = sym.pi

X = sym.simplify(sym.integrate(a*sym.exp(-i*2*œÄ*f*t), (t, -b, b)), trig=True)

podatki = {a: 1, b:1}
podatki2 = {a: 1, b:3}

p1 = sym.plot(x.subs(podatki), (t, -5, +5), line_color='C0', label=f'$b={b.subs(podatki)}$',show=False, 
              title='ƒåasovna domena', ylabel='$x(t)$', xlabel='$t$')
p2 = sym.plot(x.subs(podatki2), (t, -5, +5), line_color='C1', label=f'$b={b.subs(podatki2)}$',show=False)
p1.extend(p2)
p1.legend = True
p1.show()
p1 = sym.plot(X.subs(podatki), (f, -5, +5), line_color='C0', label=f'$b={b.subs(podatki)}$',show=False, 
              title='Frekvenƒçna domena', ylabel='$X(f)$', xlabel='$f$')
p2 = sym.plot(X.subs(podatki2), (f, -5, +5), line_color='C1', label=f'$b={b.subs(podatki2)}$',show=False)
p1.extend(p2)
p1.legend = True
p1.show()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_59688/3614761255.py[0m in [0;36m<module>[1;34m[0m
[0;32m     10[0m [0mpodatki2[0m [1;33m=[0m [1;33m{[0m[0ma[0m[1;33m:[0m [1;36m1[0m[1;33m,[0m [0mb[0m[1;33m:[0m[1;36m3[0m[1;33m}[0m[1;33m[0m[1;33m[0m[0m
[0;32m     11[0m [1;33m[0m[0m
[1;32m---> 12[1;33m p1 = sym.plot(x.subs(podatki), (t, -5, +5), line_color='C0', label=f'$b={b.subs(podatki)}$',show=False, 
[0m[0;32m     13[0m               title='ƒåasovna domena', ylabel='$x(t)$', xlabel='$t$')
[0;32m     14[0m [0mp2[0m [1;33m=[0m [0msym[0m[1;33m.[0m[0mplot[0m[1;33m([0m[0mx[0m[1;33m.[0m[0msubs[0m[1;33m([0m[0mpodatki2[0m[1;33m)[0m[1;33m,[0m [1;33m([0m[0mt[0m[1;33m,[0m [1;33m-[0m[1;36m5[0m[1;33m,[0m [1;33m+[0m[1;36m5[0m[1;33m)[0m[1;33m,[0m [0mline_color[0m[1;33m=[0m[1;34m'C1'[0m[1;33m,[0m [0mlabel[0m[1;33m=[0m[1;34mf'$b={b.subs(podatki2)}$'[0m[1;33m,[0m[0mshow[0m[1;33m=[0m[1;32mFalse[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\python39\lib\site-packages\sympy\plotting\plot.py[0m in [0;36mplot[1;34m(show, *args, **kwargs)[0m
[0;32m   1726[0m             [0mfree[0m [1;33m|=[0m [0ma[0m[1;33m.[0m[0mfree_symbols[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1727[0m             [1;32mif[0m [0mlen[0m[1;33m([0m[0mfree[0m[1;33m)[0m [1;33m>[0m [1;36m1[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1728[1;33m                 raise ValueError(
[0m[0;32m   1729[0m                     [1;34m'The same variable should be used in all '[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1730[0m                     'univariate expressions being plotted.')

[1;31mValueError[0m: The same variable should be used in all univariate expressions being plotted.
ValueError: The same variable should be used in all univariate expressions being plotted.

